from django.urls import path
from . import views

urlpatterns = [
    path(
        '', 
        views.LoginView.as_view(),
        name="auth_login"
    ),
    path(
        'auth_login/',
        views.LoginView.as_view(),
        name="auth_login"
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        'loan_book/',
        views.LoanBookView.as_view(),
        name="loan_book"
    ),
    path(
        'dashboard', 
        views.DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        'create_new_loan/',
        views.CreateNewLoanView.as_view(),
        name="create_new_loan"
    ),
    path(
        'add_new_borrower/',
        views.CreateNewBorrower.as_view(),
        name="add_new_borrower"
    ),
    path(
        'loans/',
        views.LoansView.as_view(),
        name="loans"
    ),
    path(
        'loan/<int:loan>/',
        views.ViewOneLoan.as_view(),
        name="loan"
    ),
    path(
        'create_payment/<int:loan>/',
        views.CreatePaymentView.as_view(),
        name="create_payment"
    ),
    path(
        'approve_loan/<int:loan>/',
        views.ConfirmLoan.as_view(),
        name="approve_loan"
    ),
    path(
        'members/',
        views.MembersView.as_view(),
        name="members"
    ),
    path(
        'reports/',
        views.ReportView.as_view(),
        name="reports"
    )
]