# Generated by Django 3.2 on 2023-06-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='state',
        ),
    ]
