# Generated by Django 3.2 on 2023-06-08 15:45

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20230608_1530'),
        ('loan', '0004_remove_loan_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='state',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.state'),
        ),
    ]
