# Generated by Django 3.1.3 on 2023-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='borrower_id',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='repayment_term_range',
            field=models.IntegerField(blank=True, choices=[(1, '1 Year')], default=1, null=True),
        ),
    ]
